name: synkrama
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.3.5
  video_player: ^2.4.7
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/bg.png
     - assets/videoplayback.mp4

